server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions-prod.yaml

clients:
  - url: http://10.0.1.43:80/loki/api/v1/push

scrape_configs:
  - job_name: spring-logs-info
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          env: prod
          __path__: /log/info/**/*.log

  - job_name: spring-logs-warn
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          env: prod
          __path__: /log/warn/**/*.log

  - job_name: spring-logs-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          env: prod
          __path__: /log/error/**/*.log
