server:
  # Promtail 의 HTTP 서버가 요청을 수신할 포트를 지정합니다.
  # Promtail 의 상태 페이지, 메트릭스, 로그 수집 상태 등을 확인하는 데 사용됩니다.
  http_listen_port: 9080
  # gRPC 서버가 수신할 포트를 지정합니다. 이 경우 0으로 설정되었으므로 gRPC 서버가 비활성화됩니다.
  grpc_listen_port: 0

positions:
  # 동기화 작업을 이루기 위해 promtail이 읽은 마지막 로그 정보를 저장하는 곳
  filename: /tmp/positions.yaml

clients:
  # push할 Loki의 주소
  - url: http://10.0.0.72:3100/loki/api/v1/push

scrape_configs:
  # 해당 로그 수집 작업의 이름을 정의합니다.
  - job_name: spring-logs
    static_configs:
      # 수집할 로그 파일이 있는 시스템의 대상 호스트를 지정합니다.
      - targets:
          - localhost
        labels:
          # 수집되는 로그에 추가될 메타데이터(레이블)를 정의합니다.
          # 예시 : job=varlogs
          job: varlogs
          # 수집할 로그 파일의 경로를 지정합니다.
          __path__: /log/**/*.log
