spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.performance.url}
    username: ${database.performance.username}
    password: ${database.performance.password}
    hikari:
      maximum-pool-size: 30 # RDS t3.medium 기준 최대 90
      idle-timeout: 600000 # 10분
      leak-detection-threshold: 60000 # 연결 누수 로그 설정, 1분 동안 연결 풀 반환이 일어나지 않으면 경고 로그
      minimum-idle: 5 # 유휴 상태일 때 5개만 유지
  sql:
    init:
      mode: never
      schema-locations:
      data-locations:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

  flyway:
    enabled: true
    user: ${database.performance.username}
    password: ${database.performance.password}
    locations:
      - classpath:db/migration_dev
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    encoding: UTF-8

  config:
    activate:
      on-profile: performance
    import:
      - submodule/security/database.yml
      - submodule/security/firebase.yml

server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 180

logging:
  level:
    org:
      apache:
        tomcat:
          util:
            net:
              NioEndpoint: DEBUG

auth:
  mode: test-google

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

firebase:
  enabled: false
  account:
    path: ${firebase.account.path}

jwt:
  access-token:
    expire-mills: ${jwt.access-token.dev.expire-mills}
