spring:
  profiles:
    active: local
  config:
    import:
      - submodule/security/aladin.yml
      - submodule/security/jwt.yml
      - submodule/security/aws.yml
      - submodule/security/google.yml
      - submodule/security/admin.yml
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

aladin:
  base-url: ${aladin.base-url}
  item-search-uri: ${aladin.item-search-uri}
  api-key: ${aladin.api-key}
  item-lookup-uri: ${aladin.item-lookup-uri}

jwt:
  secret-key: ${jwt.secret-key}
  access-token:
    expire-mills: ${jwt.access-token.expire-mills}
  refresh-token:
    expire-mills: ${jwt.refresh-token.expire-mills}
  temp-token:
    expire-mills: ${jwt.temp-token.expire-mills}

cloud:
  aws:
    s3:
      bucket: ${cloud.aws.s3.bucket}
      key-prefix: ${cloud.aws.s3.key-prefix}
      region: ${cloud.aws.s3.region}

google:
  client-id: ${google.client-id}

admin:
  email-path: ${admin.email-path}
  password: ${admin.password}
