spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.dev.url}
    username: ${database.dev.username}
    password: ${database.dev.password}
  sql:
    init:
      mode: never
      schema-locations:
      data-locations:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

  flyway:
    enabled: true
    user: ${database.dev.username}
    password: ${database.dev.password}
    locations:
      - classpath:db/migration_dev
      - classpath:db/seed_dev
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    encoding: UTF-8

  config:
    activate:
      on-profile: dev
    import:
      - submodule/security/database.yml
      - submodule/security/firebase.yml

auth:
  mode: google

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

server:
  tomcat:
    mbeanregistry:
      enabled: true
    max-http-form-post-size: 5MB
    max-swallow-size: 5MB

firebase:
  enabled: true
  account:
    path: ${firebase.account.path}

jwt:
  access-token:
    expire-mills: ${jwt.access-token.dev.expire-mills}
