name: Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SECRETS_SUBMODULE_ACCESS_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Assemble Build
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build & Push
        run: |
          docker buildx build -f Dockerfile.prod --platform linux/arm64 -t woowajeff/todoktodok:prod --push .

  cd:
    needs: ci
    runs-on: [self-hosted, prod]
    steps:
      - name: Cleanup backend log directory before checkout
        run: |
          sudo chown -R ubuntu:ubuntu backend/log
          sudo rm -rf backend/log || true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRETS_SUBMODULE_ACCESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Stop running Container (without removing)
        run: |
          echo "prod 컨테이너 중지 중..."
          docker stop prod && echo "prod 컨테이너 중지 완료" || echo "prod 컨테이너 없음"
          echo "promtail_prod 컨테이너 중지 중..."
          docker stop promtail_prod && echo "promtail_prod 컨테이너 중지 완료" || echo "promtail_prod 컨테이너 없음"

      - name: Docker Compose Pull & Up (no-build)
        env:
          ENV_ID: ${{ github.run_id }}
        run: |
          cd backend
          echo "ENV_ID: $ENV_ID"
          docker compose -f config/docker-compose-prod.yml pull
          docker compose -f config/docker-compose-prod.yml up -d --no-build
          echo "docker compose-prod up"

      - name: Docker image Prune
        run: |
          echo "24시간 이상 사용되지 않은 Docker 이미지 정리 중..."
          sudo docker image prune -f --filter "until=24h"
          echo "이미지 정리 완료"
